#  environment document

name: emgandash
channels:
  - conda-forge
dependencies:
  - python=3.8.6

  - dash=2.4.1
  - ipympl
  - ipywidgets=7.7.0
  - jupyter=1.0.0
  - matplotlib=3.3.3
  - mne=0.21.2
  - notebook=6.4.10
  - numexpr=2.7.3
  - numpy=1.22.3
  - pandas
  - pip=20.2
  - pyxdf
  - sphinx=4.5.0
  - textdistance =4.2.1



  - pip:
    
 
    # - tensorflow==2.4.1
    # - jupyterlab-pygments==0.2.0
    # - jupyterlab-widgets==1.1.0
    # - jupyter-core==4.9.2
    # - jupyter-console==6.4.3
    - mcfly==3.1.0
    - dash-uploader==0.6.0
    # - jupyter-client==7.2.2
